### ISSUE TITLE
Let user edit text of a todo

### ISSUE THREAD

**Issue by yamid** [yamid/todos-using-react-hooks#1]

**Comment by smkamranqadri** [comment]
I am taking this issue.

**Comment by smkamranqadri** [comment]
PR #2 generated

**Comment by yamid** [comment]
Thank you so much, happy hacktoberfest!

**Comment by smkamranqadri** [comment]
How about hosting this on github pages? create an issue, I'll do it.

**Comment by yamid** [comment]
I want to host it on Firebase

**Comment by smkamranqadri** [comment]
Sure, but just a question why you want to do on firebase, since you are not using firebase.

**Comment by yamid** [comment]
Because I'll use it for authentication and database.

**Comment by smkamranqadri** [comment]
Sure, I'll work on it.

**Comment by smkamranqadri** [comment]
Please assign me

**Comment by yamid** [comment]
Comment on #5 so I can assign you

**Comment by smkamranqadri** [comment]
Yes please
