### ISSUE TITLE
Authentication with Firebase

### ISSUE THREAD

**Issue by yamid** [yamid/todos-using-react-hooks#5]
Integrate with firebase for authentication.

**Comment by gwom5** [comment]
Could you please provide the firebase access details

**Comment by HarisSpahija** [comment]
Hi, is there any update on this? I would also like to contribute

**Comment by yamid** [comment]
ok, then I'll open an issue for authentication and for saving todos, just comment which one you want to work on. 

If you need access to firebase console I'll need your gmail.

**Comment by HarisSpahija** [comment]
Yow, I would avoid posting your firebase configuration like that public github. This can and will be hijacked by bots.

**Comment by yamid** [comment]
What access do you need then?

**Comment by gwom5** [comment]
my email is chomogwom@gmail.com. Would like to do the auth and possibly saving todos

**Comment by yamid** [comment]
OK I have given you access, I guess you have received an email, if not, login to firebase console and look for the project **todolist-9831c**
